// Extra products (raw) generated from user-provided list.
// These are minimal objects; `lib/products.ts` will append them and add the materials list.
// Base extra products explicitly listed (bannere etc.)
const BASE_EXTRA_PRODUCTS_RAW: any[] = [
  { id: "banner-curatenie-profesionala", slug: "curatenie-profesionala", routeSlug: "curatenie-profesionala", title: "Banner - Curățenie profesională", description: "Banner pentru servicii de curățenie profesională.", images: ["/products/banner/curatenie-profesionala.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["curatenie","curatenie-profesionala"], metadata: { category: "bannere" } },
  { id: "banner-magazin-second-hand", slug: "magazin-second-hand", routeSlug: "magazin-second-hand", title: "Banner - Magazin second hand", description: "Banner pentru magazine second hand.", images: ["/products/banner/magazin-second-hand.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["second-hand","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-electrocasnice", slug: "magazin-electrocasnice", routeSlug: "magazin-electrocasnice", title: "Banner - Magazin electrocasnice", description: "Banner pentru magazine de electrocasnice.", images: ["/products/banner/magazin-electrocasnice.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["electrocasnice","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-gsm", slug: "magazin-gsm", routeSlug: "magazin-gsm", title: "Banner - Magazin GSM", description: "Banner pentru magazine GSM și accesorii.", images: ["/products/banner/magazin-gsm.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["gsm","telefoane"], metadata: { category: "bannere" } },
  { id: "banner-service-telefoane", slug: "service-telefoane", routeSlug: "service-telefoane", title: "Banner - Service telefoane", description: "Banner pentru service telefoane și reparații.", images: ["/products/banner/service-telefoane.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["service","telefoane"], metadata: { category: "bannere" } },
  { id: "banner-magazin-piese-auto", slug: "magazin-piese-auto", routeSlug: "magazin-piese-auto", title: "Banner - Magazin piese auto", description: "Banner pentru magazine de piese auto.", images: ["/products/banner/magazin-piese-auto.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["piese-auto","auto"], metadata: { category: "bannere" } },
  { id: "banner-magazin-decoratiuni", slug: "magazin-decoratiuni", routeSlug: "magazin-decoratiuni", title: "Banner - Magazin decorațiuni", description: "Banner pentru magazine de decorațiuni.", images: ["/products/banner/magazin-decoratiuni.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["decoratiuni","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-papetarie", slug: "magazin-papetarie", routeSlug: "magazin-papetarie", title: "Banner - Magazin papetărie", description: "Banner pentru papetării și rechizite.", images: ["/products/banner/magazin-papetarie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["papetarie","rechizite"], metadata: { category: "bannere" } },
  { id: "banner-magazin-animale-de-companie", slug: "magazin-animale-de-companie", routeSlug: "magazin-animale-de-companie", title: "Banner - Magazin animale de companie", description: "Banner pentru magazine și produse pentru animale de companie.", images: ["/products/banner/magazin-animale-de-companie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["animale","pet-shop"], metadata: { category: "bannere" } },
  { id: "banner-pet-shop", slug: "pet-shop", routeSlug: "pet-shop", title: "Banner - Pet Shop", description: "Banner pentru pet shop și produse animale.", images: ["/products/banner/pet-shop.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["pet-shop","animale"], metadata: { category: "bannere" } },
  { id: "banner-magazin-sport", slug: "magazin-sport", routeSlug: "magazin-sport", title: "Banner - Magazin sport", description: "Banner pentru magazine de articole sportive.", images: ["/products/banner/magazin-sport.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["sport","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-pescuit", slug: "magazin-pescuit", routeSlug: "magazin-pescuit", title: "Banner - Magazin pescuit", description: "Banner pentru magazine de pescuit și accesorii.", images: ["/products/banner/magazin-pescuit.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["pescuit","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-mobila", slug: "magazin-mobila", routeSlug: "magazin-mobila", title: "Banner - Magazin mobilă", description: "Banner pentru magazine de mobilier.", images: ["/products/banner/magazin-mobila.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["mobila","mobilă"], metadata: { category: "bannere" } },
  { id: "banner-mobila-la-comanda", slug: "mobila-la-comanda", routeSlug: "mobila-la-comanda", title: "Banner - Mobilă la comandă", description: "Banner pentru mobilier la comandă.", images: ["/products/banner/mobila-la-comanda.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["mobilă","la-comandă"], metadata: { category: "bannere" } },
  { id: "banner-panificatie", slug: "panificatie", routeSlug: "panificatie", title: "Banner - Panificație", description: "Banner pentru panificație și brutării.", images: ["/products/banner/panificatie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["panificatie","brutarie"], metadata: { category: "bannere" } },
  { id: "banner-brutarie", slug: "brutarie", routeSlug: "brutarie", title: "Banner - Brutărie", description: "Banner pentru brutării.", images: ["/products/banner/brutarie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["brutarie","panificatie"], metadata: { category: "bannere" } },
  { id: "banner-cafenea", slug: "cafenea", routeSlug: "cafenea", title: "Banner - Cafenea", description: "Banner pentru cafenele.", images: ["/products/banner/cafenea.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["cafenea","cafea"], metadata: { category: "bannere" } },
  { id: "banner-restaurant", slug: "restaurant", routeSlug: "restaurant", title: "Banner - Restaurant", description: "Banner pentru restaurante.", images: ["/products/banner/restaurant.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["restaurant","mancare"], metadata: { category: "bannere" } },
  { id: "banner-pizzerie", slug: "pizzerie", routeSlug: "pizzerie", title: "Banner - Pizzerie", description: "Banner pentru pizzerii.", images: ["/products/banner/pizzerie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["pizzerie","pizza"], metadata: { category: "bannere" } },
  { id: "banner-terasa", slug: "terasa", routeSlug: "terasa", title: "Banner - Terasă", description: "Banner pentru terase și locuri de relaxare.", images: ["/products/banner/terasa.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["terasa","restaurant"], metadata: { category: "bannere" } },
  { id: "banner-livram-la-domiciliu", slug: "livram-la-domiciliu", routeSlug: "livram-la-domiciliu", title: "Banner - Livrăm la domiciliu", description: "Banner pentru servicii de livrare la domiciliu.", images: ["/products/banner/livram-la-domiciliu.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["livrare","delivery"], metadata: { category: "bannere" } },
  { id: "banner-deschis-acum", slug: "deschis-acum", routeSlug: "deschis-acum", title: "Banner - Deschis acum", description: "Banner pentru afișarea mesajului 'Deschis acum'.", images: ["/products/banner/deschis-acum.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["deschis","open"], metadata: { category: "bannere" } },
  { id: "banner-deschis-24-7", slug: "deschis-24-7", routeSlug: "deschis-24-7", title: "Banner - Deschis 24/7", description: "Banner pentru afișarea programului 24/7.", images: ["/products/banner/deschis-24-7.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["deschis","24-7"], metadata: { category: "bannere" } },
  { id: "banner-acces-interzis", slug: "acces-interzis", routeSlug: "acces-interzis", title: "Banner - Acces interzis", description: "Banner pentru semnalizare 'Acces interzis'.", images: ["/products/banner/acces-interzis.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["acces","interzis"], metadata: { category: "bannere" } },
  { id: "banner-parcare-privata", slug: "parcare-privata", routeSlug: "parcare-privata", title: "Banner - Parcare privată", description: "Banner pentru semnalizarea parcărilor private.", images: ["/products/banner/parcare-privata.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["parcare","privata"], metadata: { category: "bannere" } },
  { id: "banner-inchis-pentru-renovare", slug: "inchis-pentru-renovare", routeSlug: "inchis-pentru-renovare", title: "Banner - Închis pentru renovare", description: "Banner pentru anunțuri 'Închis pentru renovare'.", images: ["/products/banner/inchis-pentru-renovare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["inchis","renovare"], metadata: { category: "bannere" } },
  { id: "banner-recrutam-personal", slug: "recrutam-personal", routeSlug: "recrutam-personal", title: "Banner - Recrutăm personal", description: "Banner pentru anunțuri de recrutare.", images: ["/products/banner/recrutam-personal.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["recrutare","angajam"], metadata: { category: "bannere" } },
  { id: "banner-angajam", slug: "angajam", routeSlug: "angajam", title: "Banner - Angajăm!", description: "Banner pentru anunțuri 'Angajăm'.", images: ["/products/banner/angajam.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["angajam","job"], metadata: { category: "bannere" } },
  { id: "banner-oferta-valabila-pana-la", slug: "oferta-valabila-pana-la", routeSlug: "oferta-valabila-pana-la", title: "Banner - Ofertă valabilă până la...", description: "Banner pentru oferte cu termen limită.", images: ["/products/banner/oferta-valabila-pana-la.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["oferta","promo"], metadata: { category: "bannere" } },
  { id: "banner-noua-colectie-a-sosit", slug: "noua-colectie-a-sosit", routeSlug: "noua-colectie-a-sosit", title: "Banner - Noua colecție a sosit", description: "Banner pentru anunțuri 'Noua colecție a sosit'.", images: ["/products/banner/noua-colectie-a-sosit.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["colectie","nou"], metadata: { category: "bannere" } },
  { id: "banner-in-stoc-limitat", slug: "in-stoc-limitat", routeSlug: "in-stoc-limitat", title: "Banner - În stoc limitat", description: "Banner pentru anunțuri 'În stoc limitat'.", images: ["/products/banner/in-stoc-limitat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["stoc","limitat"], metadata: { category: "bannere" } },
  { id: "banner-produse-noi-disponibile", slug: "produse-noi-disponibile", routeSlug: "produse-noi-disponibile", title: "Banner - Produse noi disponibile", description: "Banner pentru anunțuri 'Produse noi disponibile'.", images: ["/products/banner/produse-noi-disponibile.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["produse-noi","nou"], metadata: { category: "bannere" } },
  { id: "banner-inchiriere-utilaje", slug: "inchiriere-utilaje", routeSlug: "inchiriere-utilaje", title: "Banner - Închiriere utilaje", description: "Banner pentru servicii de închiriere utilaje.", images: ["/products/banner/inchiriere-utilaje.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["inchiriere","utilaje"], metadata: { category: "bannere" } },
  { id: "banner-tipografie", slug: "tipografie", routeSlug: "tipografie", title: "Banner - Tipografie", description: "Banner pentru servicii de tipografie.", images: ["/products/banner/tipografie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["tipografie","print"], metadata: { category: "bannere" } },
  { id: "banner-centru-de-copiere", slug: "centru-de-copiere", routeSlug: "centru-de-copiere", title: "Banner - Centru de copiere", description: "Banner pentru centre de copiere și print.", images: ["/products/banner/centru-de-copiere.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["copiere","print"], metadata: { category: "bannere" } },
  { id: "banner-croitorie-retusuri", slug: "croitorie-retusuri", routeSlug: "croitorie-retusuri", title: "Banner - Croitorie / Retușuri", description: "Banner pentru croitorii și servicii de retuș.", images: ["/products/banner/croitorie-retusuri.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["croitorie","retusuri"], metadata: { category: "bannere" } },
  { id: "banner-curatenie-la-domiciliu", slug: "curatenie-la-domiciliu", routeSlug: "curatenie-la-domiciliu", title: "Banner - Curățenie la domiciliu", description: "Banner pentru servicii de curățenie la domiciliu.", images: ["/products/banner/curatenie-la-domiciliu.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["curatenie","domiciliu"], metadata: { category: "bannere" } },
  { id: "banner-atelier-mecanic", slug: "atelier-mecanic", routeSlug: "atelier-mecanic", title: "Banner - Atelier mecanic", description: "Banner pentru ateliere mecanice.", images: ["/products/banner/atelier-mecanic.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["atelier","mecanic"], metadata: { category: "bannere" } },
  { id: "banner-detailing-auto", slug: "detailing-auto", routeSlug: "detailing-auto", title: "Banner - Detailing auto", description: "Banner pentru servicii de detailing auto.", images: ["/products/banner/detailing-auto.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["detailing","auto"], metadata: { category: "bannere" } },
  { id: "banner-depozit-materiale-constructii", slug: "depozit-materiale-constructii", routeSlug: "depozit-materiale-constructii", title: "Banner - Depozit materiale construcții", description: "Banner pentru depozite și materiale de construcții.", images: ["/products/banner/depozit-materiale-constructii.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["constructii","materiale"], metadata: { category: "bannere" } },
  { id: "banner-inchiriere-birouri", slug: "inchiriere-birouri", routeSlug: "inchiriere-birouri", title: "Banner - Închiriere birouri", description: "Banner pentru anunțuri de închiriere birouri.", images: ["/products/banner/inchiriere-birouri.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["inchiriere","birouri"], metadata: { category: "bannere" } },
  { id: "banner-showroom-deschis", slug: "showroom-deschis", routeSlug: "showroom-deschis", title: "Banner - Showroom deschis", description: "Banner pentru anunțul 'Showroom deschis'.", images: ["/products/banner/showroom-deschis.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["showroom","deschis"], metadata: { category: "bannere" } },
  { id: "banner-lustragiu-cizmărie", slug: "lustragiu-cizmărie", routeSlug: "lustragiu-cizmărie", title: "Banner - Lustragiu / Cizmărie", description: "Banner pentru servicii de lustragiu și cizmărie.", images: ["/products/banner/lustragiu-cizmarie.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["lustragiu","cizmărie"], metadata: { category: "bannere" } },
  { id: "banner-curier-local", slug: "curier-local", routeSlug: "curier-local", title: "Banner - Curier local", description: "Banner pentru servicii de curierat local.", images: ["/products/banner/curier-local.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["curier","local"], metadata: { category: "bannere" } },
  { id: "banner-transport-marfa", slug: "transport-marfa", routeSlug: "transport-marfa", title: "Banner - Transport marfă", description: "Banner pentru servicii de transport marfă.", images: ["/products/banner/transport-marfa.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["transport","marfa"], metadata: { category: "bannere" } },
  { id: "banner-livram-in-toata-tara", slug: "livram-in-toata-tara", routeSlug: "livram-in-toata-tara", title: "Banner - Livrăm în toată țara", description: "Banner pentru servicii cu livrare națională.", images: ["/products/banner/livram-in-toata-tara.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["livrare","national"], metadata: { category: "bannere" } },
  { id: "banner-magazin-handmade", slug: "magazin-handmade", routeSlug: "magazin-handmade", title: "Banner - Magazin handmade", description: "Banner pentru magazine handmade și creativi.", images: ["/products/banner/magazin-handmade.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["handmade","magazin"], metadata: { category: "bannere" } },
  { id: "banner-cadouri-personalizate", slug: "cadouri-personalizate", routeSlug: "cadouri-personalizate", title: "Banner - Cadouri personalizate", description: "Banner pentru cadouri personalizate.", images: ["/products/banner/cadouri-personalizate.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["cadouri","personalizate"], metadata: { category: "bannere" } },
  { id: "banner-produse-bio-eco", slug: "produse-bio-eco", routeSlug: "produse-bio-eco", title: "Banner - Produse bio / eco", description: "Banner pentru produse bio și eco.", images: ["/products/banner/produse-bio-eco.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["bio","eco"], metadata: { category: "bannere" } },
  { id: "banner-atelier-bijuterii", slug: "atelier-bijuterii", routeSlug: "atelier-bijuterii", title: "Banner - Atelier bijuterii", description: "Banner pentru ateliere de bijuterii.", images: ["/products/banner/atelier-bijuterii.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["bijuterii","atelier"], metadata: { category: "bannere" } },
  { id: "banner-cofetarie-artizanala", slug: "cofetarie-artizanala", routeSlug: "cofetarie-artizanala", title: "Banner - Cofetărie artizanală", description: "Banner pentru cofetării artizanale.", images: ["/products/banner/cofetarie-artizanala.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["cofetarie","artizanal"], metadata: { category: "bannere" } },
  { id: "banner-incearca-noul-produs", slug: "incearca-noul-produs", routeSlug: "incearca-noul-produs", title: "Banner - Încearcă noul produs", description: "Banner pentru promovarea unui produs nou.", images: ["/products/banner/incearca-noul-produs.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["nou","promo"], metadata: { category: "bannere" } },
  { id: "banner-lichidare-totala", slug: "lichidare-totala", routeSlug: "lichidare-totala", title: "Banner - Lichidare totală", description: "Banner pentru lichidare totală de stoc.", images: ["/products/banner/lichidare-totala.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["lichidare","stoc"], metadata: { category: "bannere" } },
  { id: "banner-promotie-de-vara", slug: "promotie-de-vara", routeSlug: "promotie-de-vara", title: "Banner - Promoție de vară", description: "Banner pentru campanii de vară.", images: ["/products/banner/promotie-de-vara.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["vara","promo"], metadata: { category: "bannere" } },
  { id: "banner-reduceri-de-toamna", slug: "reduceri-de-toamna", routeSlug: "reduceri-de-toamna", title: "Banner - Reduceri de toamnă", description: "Banner pentru reduceri de toamnă.", images: ["/products/banner/reduceri-de-toamna.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["reduceri","toamna"], metadata: { category: "bannere" } },
  { id: "banner-black-friday", slug: "black-friday", routeSlug: "black-friday", title: "Banner - Black Friday", description: "Banner pentru campanii Black Friday.", images: ["/products/banner/black-friday.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["black-friday","promo"], metadata: { category: "bannere" } },
  { id: "banner-winter-sale", slug: "winter-sale", routeSlug: "winter-sale", title: "Banner - Winter Sale", description: "Banner pentru oferte de iarnă.", images: ["/products/banner/winter-sale.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["sale","winter"], metadata: { category: "bannere" } },
  { id: "banner-oferta-exclusiva", slug: "oferta-exclusiva", routeSlug: "oferta-exclusiva", title: "Banner - Ofertă exclusivă", description: "Banner pentru oferte exclusive.", images: ["/products/banner/oferta-exclusiva.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["oferta","exclusiv"], metadata: { category: "bannere" } },
  { id: "banner-reparatii-laptopuri", slug: "reparatii-laptopuri", routeSlug: "reparatii-laptopuri", title: "Banner - Reparații laptopuri", description: "Banner pentru service laptopuri.", images: ["/products/banner/reparatii-laptopuri.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["reparatii","laptopuri"], metadata: { category: "bannere" } },
  { id: "banner-magazin-electronice", slug: "magazin-electronice", routeSlug: "magazin-electronice", title: "Banner - Magazin electronice", description: "Banner pentru magazine electronice.", images: ["/products/banner/magazin-electronice.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["electronice","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-electro-it", slug: "magazin-electro-it", routeSlug: "magazin-electro-it", title: "Banner - Magazin electro IT", description: "Banner pentru magazine electro IT.", images: ["/products/banner/magazin-electro-it.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["electro","it"], metadata: { category: "bannere" } },
  { id: "banner-reparam-telefoane", slug: "reparam-telefoane", routeSlug: "reparam-telefoane", title: "Banner - Reparăm telefoane", description: "Banner pentru servicii de reparații telefoane.", images: ["/products/banner/reparam-telefoane.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["reparatii","telefoane"], metadata: { category: "bannere" } },
  { id: "banner-magazin-incaltaminte", slug: "magazin-incaltaminte", routeSlug: "magazin-incaltaminte", title: "Banner - Magazin încălțăminte", description: "Banner pentru magazine de încălțăminte.", images: ["/products/banner/magazin-incaltaminte.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["incaltaminte","magazin"], metadata: { category: "bannere" } },
  { id: "banner-magazin-haine", slug: "magazin-haine", routeSlug: "magazin-haine", title: "Banner - Magazin haine", description: "Banner pentru magazine de haine.", images: ["/products/banner/magazin-haine.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["haine","magazin"], metadata: { category: "bannere" } }
  ,
  // Moved from lib/products.ts (BASE_PRODUCTS) as requested
  { id: "banner-apartament-de-inchiriat", slug: "apartament-de-inchiriat", routeSlug: "apartament-de-inchiriat", title: "Banner - Apartament de închiriat", description: "Banner personalizat pentru promovarea apartamentelor de închiriat. Configurează dimensiuni, material și finisaje.", images: ["/products/banner/apartament-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["banner","apartament","inchiriat"], metadata: { category: "bannere" } },
  { id: "banner-apartament-de-vanzare", slug: "apartament-de-vanzare", routeSlug: "apartament-de-vanzare", title: "Banner - Apartament de vânzare", description: "Banner personalizat pentru apartamente de vânzare.", images: ["/products/banner/apartament-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["banner","apartament","vanzare"], metadata: { category: "bannere" } },
  { id: "banner-barbershop", slug: "barbershop", routeSlug: "barbershop", title: "Banner Barber Shop", description: "Banner pentru frizerii și barber-shop-uri.", images: ["/products/banner/barbershop.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["barbershop","banner"], metadata: { category: "bannere" } },
  { id: "banner-cabinet-stomatologic", slug: "cabinet-stomatologic", routeSlug: "cabinet-stomatologic", title: "Banner Cabinet Stomatologic", description: "Banner pentru cabinete stomatologice și anunțuri medicale.", images: ["/products/banner/cabinet-stomatologic.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["stomatologie","banner"], metadata: { category: "bannere" } },
  { id: "banner-casa-de-inchiriat", slug: "casa-de-inchiriat", routeSlug: "casa-de-inchiriat", title: "Banner - Casă de închiriat", description: "Banner pentru proprietăţi de închiriat.", images: ["/products/banner/casa-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["casa","inchiriat","banner"], metadata: { category: "bannere" } },
  { id: "banner-casa-de-vanzare", slug: "casa-de-vanzare", routeSlug: "casa-de-vanzare", title: "Banner - Casă de vânzare", description: "Banner pentru proprietăţi de vânzare.", images: ["/products/banner/casa-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["casa","vanzare","banner"], metadata: { category: "bannere" } },
  { id: "banner-de-inchiriat", slug: "de-inchiriat", routeSlug: "de-inchiriat", title: "Banner - De închiriat", description: "Banner generic pentru anunţuri 'de închiriat'.", images: ["/products/banner/de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["inchiriere","banner"], metadata: { category: "bannere" } },
  { id: "banner-fastfood", slug: "fastfood", routeSlug: "fastfood", title: "Banner Fast-Food", description: "Banner pentru restaurante de tip fast-food și livrări.", images: ["/products/banner/fastfood.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["food","fastfood","banner"], metadata: { category: "bannere" } },
  { id: "banner-fructe-si-legume", slug: "fructe-si-legume", routeSlug: "fructe-si-legume", title: "Banner Fructe și Legume", description: "Banner pentru pieţe, tarabe și magazine de fructe și legume.", images: ["/products/banner/fructe-si-legume.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["fructe","legume","banner"], metadata: { category: "bannere" } },
  { id: "banner-garsoniera-de-inchiriat", slug: "garsoniera-de-inchiriat", routeSlug: "garsoniera-de-inchiriat", title: "Banner Garsonieră de închiriat", description: "Banner pentru garsoniere de închiriat.", images: ["/products/banner/garsoniera-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["garsoniera","inchiriat","banner"], metadata: { category: "bannere" } },
  { id: "banner-garsoniera-de-vanzare", slug: "garsoniera-de-vanzare", routeSlug: "garsoniera-de-vanzare", title: "Banner Garsonieră de vânzare", description: "Banner pentru garsoniere de vânzare.", images: ["/products/banner/garsoniera-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["garsoniera","vanzare","banner"], metadata: { category: "bannere" } },
  { id: "banner-la-multi-ani", slug: "la-multi-ani", routeSlug: "la-multi-ani", title: "Banner La mulți ani!", description: "Banner de felicitare pentru aniversări și evenimente.", images: ["/products/banner/la-multi-ani.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["la-multi-ani","banner"], metadata: { category: "bannere" } },
  { id: "banner-magazin-alimentar", slug: "magazin-alimentar", routeSlug: "magazin-alimentar", title: "Banner Magazin Alimentar", description: "Banner pentru magazine alimentare și promoții.", images: ["/products/banner/magazin-alimentar.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["magazin","alimentar","banner"], metadata: { category: "bannere" } },
  { id: "banner-nu-blocati", slug: "nu-blocati", routeSlug: "nu-blocati", title: "Banner Nu blocați", description: "Banner pentru avertismente — 'Nu blocați'.", images: ["/products/banner/nu-blocati.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["semnalistica","banner"], metadata: { category: "bannere" } },
  { id: "banner-produs-in-romania", slug: "produs-in-romania", routeSlug: "produs-in-romania", title: "Banner – Produs în România", description: "Banner care marchează originile produsului 'Produs în România'.", images: ["/products/banner/produs-in-romania.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["produs","romania","banner"], metadata: { category: "bannere" } },
  { id: "banner-rent-a-car", slug: "rent-a-car", routeSlug: "rent-a-car", title: "Banner Rent-a-Car", description: "Banner pentru servicii de închiriere auto.", images: ["/products/banner/rent-a-car.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["auto","rent","banner"], metadata: { category: "bannere" } },
  { id: "banner-service-auto", slug: "service-auto", routeSlug: "service-auto", title: "Banner Service Auto", description: "Banner pentru service-uri auto și anunţuri tehnice.", images: ["/products/banner/service-auto.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["service","auto","banner"], metadata: { category: "bannere" } },
  { id: "banner-servicii-medicale", slug: "servicii-medicale", routeSlug: "servicii-medicale", title: "Banner Servicii medicale", description: "Banner pentru clinici și servicii medicale.", images: ["/products/banner/servicii-medicale.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["medical","banner"], metadata: { category: "bannere" } },
  { id: "banner-spalatorie-haine", slug: "spalatorie-haine", routeSlug: "spalatorie-haine", title: "Banner Spălătorie haine", description: "Banner pentru spălătorii auto sau de haine.", images: ["/products/banner/spalatorie-haine.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["spalatorie","banner"], metadata: { category: "bannere" } },
  { id: "banner-spatiu-de-inchiriat", slug: "spatiu-de-inchiriat", routeSlug: "spatiu-de-inchiriat", title: "Banner Spaţiu de închiriat", description: "Banner pentru spaţii comerciale sau industriale de închiriat.", images: ["/products/banner/spatiu-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["spatiu","inchiriat","banner"], metadata: { category: "bannere" } },
  { id: "banner-spatiu-de-vanzare", slug: "spatiu-de-vanzare", routeSlug: "spatiu-de-vanzare", title: "Banner Spaţiu de vânzare", description: "Banner pentru spaţii de vânzare.", images: ["/products/banner/spatiu-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["spatiu","vanzare","banner"], metadata: { category: "bannere" } },
  { id: "banner-teren-de-inchiriat", slug: "teren-de-inchiriat", routeSlug: "teren-de-inchiriat", title: "Banner Teren de închiriat", description: "Banner pentru terenuri de închiriat (teren, loturi).", images: ["/products/banner/teren-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["teren","inchiriat","banner"], metadata: { category: "bannere" } },
  { id: "banner-teren-de-vanzare", slug: "teren-de-vanzare", routeSlug: "teren-de-vanzare", title: "Banner Teren de vânzare", description: "Banner pentru terenuri de vânzare.", images: ["/products/banner/teren-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["teren","vanzare","banner"], metadata: { category: "bannere" } },
  { id: "banner-vila-de-inchiriat", slug: "vila-de-inchiriat", routeSlug: "vila-de-inchiriat", title: "Banner Vilă de închiriat", description: "Banner pentru vile de închiriat.", images: ["/products/banner/vila-de-inchiriat.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["vila","inchiriat","banner"], metadata: { category: "bannere" } },
  { id: "banner-vila-de-vanzare", slug: "vila-de-vanzare", routeSlug: "vila-de-vanzare", title: "Banner Vilă de vânzare", description: "Banner pentru vile de vânzare.", images: ["/products/banner/vila-de-vanzare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["vila","vanzare","banner"], metadata: { category: "bannere" } },
  { id: "banner-vulcanizare", slug: "vulcanizare", routeSlug: "vulcanizare", title: "Banner Vulcanizare", description: "Banner pentru service-uri de vulcanizare și anunţuri auto.", images: ["/products/banner/vulcanizare.jpg","/products/banner/1.jpg","/products/banner/2.jpg","/products/banner/3.jpg"], priceBase: 250, currency: "RON", tags: ["vulcanizare","auto","banner"], metadata: { category: "bannere" } }
];

// Canvas product labels provided by maintainer
const EXTRA_CANVAS_LABELS: string[] = [
  "Tablou canvas Joker",
  "Tablou canvas The Godfather",
  "Tablou canvas Scarface",
  "Tablou canvas Peaky Blinders",
  "Tablou canvas Thomas Shelby",
  "Tablou canvas Money Heist",
  "Tablou canvas Pablo Escobar",
  "Tablou canvas Al Pacino",
  "Tablou canvas Tony Montana",
  "Tablou canvas Marilyn Monroe",
  "Tablou canvas Elvis Presley",
  "Tablou canvas Bob Marley",
  "Tablou canvas Freddie Mercury",
  "Tablou canvas Michael Jackson",
  "Tablou canvas Eminem",
  "Tablou canvas Tupac",
  "Tablou canvas Biggie",
  "Tablou canvas Kanye West",
  "Tablou canvas Drake",
  "Tablou canvas Travis Scott",
  "Tablou canvas Ronaldo",
  "Tablou canvas Messi",
  "Tablou canvas Jordan",
  "Tablou canvas LeBron",
  "Tablou canvas Kobe",
  "Tablou canvas Neymar",
  "Tablou canvas Mbappe",
  "Tablou canvas Beckham",
  "Tablou canvas Tiger Woods",
  "Tablou canvas Michael Schumacher",
  "Tablou canvas Ferrari",
  "Tablou canvas Lamborghini",
  "Tablou canvas Porsche",
  "Tablou canvas BMW",
  "Tablou canvas Mercedes",
  "Tablou canvas Audi",
  "Tablou canvas Bugatti",
  "Tablou canvas Mustang",
  "Tablou canvas Harley Davidson",
  "Tablou canvas Formula 1",
  "Tablou canvas MotoGP",
  "Tablou canvas Drift",
  "Tablou canvas Supercar",
  "Tablou canvas Speed",
  "Tablou canvas Fast and Furious",
  "Tablou canvas Dom Toretto",
  "Tablou canvas Batman",
  "Tablou canvas Superman",
  "Tablou canvas Spider-Man",
  "Tablou canvas Iron Man",
  "Tablou canvas Captain America",
  "Tablou canvas Deadpool",
  "Tablou canvas Venom",
  "Tablou canvas Hulk",
  "Tablou canvas Joker și Harley Quinn",
  "Tablou canvas Harley Quinn",
  "Tablou canvas Star Wars",
  "Tablou canvas Darth Vader",
  "Tablou canvas Mandalorian",
  "Tablou canvas Yoda",
  "Tablou canvas Stormtrooper",
  "Tablou canvas Matrix",
  "Tablou canvas John Wick",
  "Tablou canvas Keanu Reeves",
  "Tablou canvas 007 James Bond",
  "Tablou canvas Pulp Fiction",
  "Tablou canvas Fight Club",
  "Tablou canvas Wolf of Wall Street",
  "Tablou canvas Breaking Bad",
  "Tablou canvas Walter White",
  "Tablou canvas Pinkman",
  "Tablou canvas V for Vendetta",
  "Tablou canvas Joker Card",
  "Tablou canvas Poker Face",
  "Tablou canvas Queen of Hearts",
  "Tablou canvas King of Spades",
  "Tablou canvas Skull",
  "Tablou canvas Money",
  "Tablou canvas Dollar",
  "Tablou canvas Euro",
  "Tablou canvas Rich",
  "Tablou canvas Boss",
  "Tablou canvas Power",
  "Tablou canvas Hustle",
  "Tablou canvas Ambition",
  "Tablou canvas Motivation",
  "Tablou canvas Mindset",
  "Tablou canvas No Pain No Gain",
  "Tablou canvas Grind",
  "Tablou canvas Success",
  "Tablou canvas Luxury",
  "Tablou canvas Rolex",
  "Tablou canvas Champagne",
  "Tablou canvas Cigar",
  "Tablou canvas Money Rain",
  "Tablou canvas Rich Life",
  "Tablou canvas Street Art",
  "Tablou canvas Graffiti",
  "Tablou canvas Abstract",
  "Tablou canvas Gold",
  "Tablou canvas Black and Gold",
  "Tablou canvas Silver",
  "Tablou canvas White Line",
  "Tablou canvas Minimal",
  "Tablou canvas Urban",
  "Tablou canvas City",
  "Tablou canvas New York",
  "Tablou canvas Paris",
  "Tablou canvas London",
  "Tablou canvas Rome",
  "Tablou canvas Dubai",
  "Tablou canvas Tokyo",
  "Tablou canvas Los Angeles",
  "Tablou canvas Skyline",
  "Tablou canvas Nature",
  "Tablou canvas Mare",
  "Tablou canvas Apus",
  "Tablou canvas Pădure",
  "Tablou canvas Flori",
  "Tablou canvas Câmp de lavandă",
  "Tablou canvas Cascadă",
  "Tablou canvas Munte",
  "Tablou canvas Ocean",
  "Tablou canvas Palmieri",
  "Tablou canvas Soare",
  "Tablou canvas Cale ferată",
  "Tablou canvas Cer înstelat",
  "Tablou canvas Luna",
  "Tablou canvas Stele",
  "Tablou canvas Liniște",
  "Tablou canvas Zen",
  "Tablou canvas Buddha",
  "Tablou canvas Samurai",
  "Tablou canvas Geisha",
  "Tablou canvas Dragon",
  "Tablou canvas Tigru",
  "Tablou canvas Leu",
  "Tablou canvas Lup",
  "Tablou canvas Vultur",
  "Tablou canvas Panteră",
  "Tablou canvas Pisică",
  "Tablou canvas Câine",
  "Tablou canvas Cal",
  "Tablou canvas Bufniță",
  "Tablou canvas Peisaj marin",
  "Tablou canvas Valuri",
  "Tablou canvas Balon cu aer cald",
  "Tablou canvas Cactus",
  "Tablou canvas Femeie portret",
  "Tablou canvas Abstract modern",
  // New batch
  "Tablou canvas Matrix Neo",
  "Tablou canvas Gladiator",
  "Tablou canvas Spartacus",
  "Tablou canvas Joker Art",
  "Tablou canvas Dark Knight",
  "Tablou canvas Harley Love",
  "Tablou canvas Venom Art",
  "Tablou canvas Spider-Verse",
  "Tablou canvas Batman vs Joker",
  "Tablou canvas Superman Logo",
  "Tablou canvas Deadpool Funny",
  "Tablou canvas Iron Man Mask",
  "Tablou canvas Thanos",
  "Tablou canvas Avengers",
  "Tablou canvas Loki",
  "Tablou canvas Thor",
  "Tablou canvas Captain Marvel",
  "Tablou canvas Wonder Woman",
  "Tablou canvas Black Panther",
  "Tablou canvas Doctor Strange",
  "Tablou canvas Wolverine",
  "Tablou canvas Magneto",
  "Tablou canvas Flash",
  "Tablou canvas Aquaman",
  "Tablou canvas Joker Smoke",
  "Tablou canvas Harley Pop",
  "Tablou canvas Peaky Blinders Art",
  "Tablou canvas Money Heist Mask",
  "Tablou canvas Narcos Pablo",
  "Tablou canvas Breaking Bad Blue",
  "Tablou canvas John Wick Gun",
  "Tablou canvas 007 Classic",
  "Tablou canvas Pulp Fiction Scene",
  "Tablou canvas Fight Club Soap",
  "Tablou canvas Wolf of Wall Street Money",
  "Tablou canvas Scarface Money Power",
  "Tablou canvas Joker Smile",
  "Tablou canvas Joker Smoke Art",
  "Tablou canvas Joker Graffiti",
  "Tablou canvas Joker Love Harley",
  "Tablou canvas Joker Black White",
  "Tablou canvas Joker Abstract",
  "Tablou canvas Joker Smile Neon",
  "Tablou canvas Joker and Batman",
  "Tablou canvas Joker 2019",
  "Tablou canvas Joker Classic",
  "Tablou canvas Joker Heath Ledger",
  "Tablou canvas Joker Joaquin Phoenix",
  "Tablou canvas Joker Clown",
  "Tablou canvas Joker Card Art",
  "Tablou canvas Joker Modern",
  "Tablou canvas Joker Minimal",
  "Tablou canvas Joker Paint",
  "Tablou canvas Joker Color",
  "Tablou canvas Joker Style",
  "Tablou canvas Joker Iconic",
  "Tablou canvas Joker Pop Art",
  "Tablou canvas Joker Comic",
  "Tablou canvas Joker Smile Smoke",
  "Tablou canvas Joker Laugh",
  "Tablou canvas Joker City",
  "Tablou canvas Joker Mirror",
  "Tablou canvas Joker Abstract Neon",
  "Tablou canvas Joker Tattoo",
  "Tablou canvas Joker Art Deco",
  "Tablou canvas Joker with Harley",
  "Tablou canvas Joker Street",
  "Tablou canvas Joker Wall",
  "Tablou canvas Joker Face",
  "Tablou canvas Joker Modern Art",
  "Tablou canvas Joker Movie",
  "Tablou canvas Joker Smile Poster",
  "Tablou canvas Joker Graffiti Wall",
  "Tablou canvas Joker Style Smoke",
  "Tablou canvas Joker Legendary",
  "Tablou canvas Joker Madness",
  "Tablou canvas Joker Chaos",
  "Tablou canvas Joker Crown",
  "Tablou canvas Joker Joker",
  "Tablou canvas Joker Deluxe",
  "Tablou canvas Joker Power",
  "Tablou canvas Joker Smile Mask",
  "Tablou canvas Joker Mafia",
  "Tablou canvas Joker Classic Poster",
  "Tablou canvas Joker Portrait",
  "Tablou canvas Joker Face Paint",
  "Tablou canvas Joker Hero",
  "Tablou canvas Joker Legend",
  "Tablou canvas Joker Epic",
  "Tablou canvas Joker Movie Icon",
  "Tablou canvas Joker Smile Art",
  "Tablou canvas Joker Smoke Portrait",
  "Tablou canvas Joker Neon Light",
  "Tablou canvas Joker Comic Style",
  "Tablou canvas Joker Pop Design",
  "Tablou canvas Joker 4K",
  "Tablou canvas Joker Canvas",
  "Tablou canvas Joker Wall Art",
  "Tablou canvas Joker Abstract Paint",
  "Tablou canvas Joker Smile Scene",
  // Cars & motors batch
  "Tablou canvas Fast X",
  "Tablou canvas Ferrari Red",
  "Tablou canvas Porsche 911",
  "Tablou canvas Lamborghini Aventador",
  "Tablou canvas BMW M4",
  "Tablou canvas Mercedes AMG GT",
  "Tablou canvas Audi RS7",
  "Tablou canvas Bugatti Veyron",
  "Tablou canvas McLaren",
  "Tablou canvas Supra",
  "Tablou canvas Skyline GT-R",
  "Tablou canvas Mustang GT",
  "Tablou canvas Camaro",
  "Tablou canvas Harley Davidson Logo",
  "Tablou canvas Motorbike",
  "Tablou canvas Speed Car",
  "Tablou canvas Drift Smoke",
  "Tablou canvas Racing Legend",
  "Tablou canvas Classic Car",
  "Tablou canvas Supercar Poster",
  "Tablou canvas Formula 1 Max Verstappen",
  "Tablou canvas Lewis Hamilton",
  "Tablou canvas Ferrari Logo",
  "Tablou canvas Porsche Logo",
  "Tablou canvas Lamborghini Logo",
  "Tablou canvas BMW Logo",
  "Tablou canvas Audi Logo",
  "Tablou canvas Mercedes Logo",
  "Tablou canvas Bugatti Logo",
  "Tablou canvas Sport Car Poster",
  "Tablou canvas Street Racing",
  "Tablou canvas Drift King",
  "Tablou canvas Turbo Boost",
  "Tablou canvas Speed Hunter",
  "Tablou canvas Classic Porsche",
  "Tablou canvas F1 Legend",
  "Tablou canvas Supercar Garage",
  "Tablou canvas Ferrari Garage",
  "Tablou canvas Porsche Dream",
  "Tablou canvas Lamborghini Dream",
  "Tablou canvas BMW Garage",
  "Tablou canvas Audi Garage",
  "Tablou canvas Mercedes Garage",
  "Tablou canvas Bugatti Garage",
  "Tablou canvas Car Lifestyle",
  "Tablou canvas Drift Style",
  "Tablou canvas Street Car",
  "Tablou canvas Speed Style",
  "Tablou canvas Race Legend",
  "Tablou canvas F1 Classic",
  "Tablou canvas Ferrari Evolution",
  "Tablou canvas Porsche Evolution",
  "Tablou canvas Lamborghini Evolution",
  "Tablou canvas BMW Evolution",
  "Tablou canvas Audi Evolution",
  "Tablou canvas Mercedes Evolution",
  "Tablou canvas Bugatti Evolution",
  "Tablou canvas Drift Machine",
  "Tablou canvas Turbo Art",
  "Tablou canvas Engine Power",
  "Tablou canvas Speed Motion",
  "Tablou canvas Racing Fuel",
  "Tablou canvas Street Performance",
  "Tablou canvas Exotic Car",
  "Tablou canvas Sport Icon",
  "Tablou canvas Racing Passion",
  "Tablou canvas Car Poster",
  "Tablou canvas Racing Heart",
  "Tablou canvas Motorsport",
  "Tablou canvas Race Life",
  "Tablou canvas Street Kings",
  "Tablou canvas Garage King",
  "Tablou canvas Drift Smoke Art",
  "Tablou canvas Ferrari Speed",
  "Tablou canvas Lamborghini Fire",
  "Tablou canvas Porsche Motion",
  "Tablou canvas BMW Drift",
  "Tablou canvas Mercedes Speed",
  "Tablou canvas Audi Drift",
  "Tablou canvas Bugatti Speed",
  "Tablou canvas Classic Speed",
  "Tablou canvas Race Dream",
  "Tablou canvas Motorsport Legend",
  "Tablou canvas Car Lovers",
  "Tablou canvas Fast Drive",
  "Tablou canvas Street Style",
  "Tablou canvas Garage Dreams",
  "Tablou canvas Power Car",
  "Tablou canvas Muscle Car",
  "Tablou canvas Turbo Life",
  "Tablou canvas Car Addict",
  "Tablou canvas Race Addict",
  "Tablou canvas Drift Addict",
  "Tablou canvas Speed Addict",
  "Tablou canvas Fast Addict",
  "Tablou canvas Car Power",
  "Tablou canvas Drift Power",
  "Tablou canvas Race Power",
  "Tablou canvas Engine King",
  "Tablou canvas Road Legend",
];

function slugify(input: string): string {
  let s = input.replace(/^Tablou\s+canvas\s+/i, "").trim();
  // Normalize common diacritics/accents
  const map: Record<string, string> = {
    "ă": "a", "â": "a", "î": "i", "ș": "s", "ş": "s", "ț": "t", "ţ": "t",
    "Ă": "a", "Â": "a", "Î": "i", "Ș": "s", "Ş": "s", "Ț": "t", "Ţ": "t",
    "é": "e", "è": "e", "ê": "e", "ë": "e",
  "á": "a", "à": "a", "ä": "a", "ã": "a",
    "í": "i", "ì": "i", "ï": "i",
    "ó": "o", "ò": "o", "ö": "o", "ô": "o",
    "ú": "u", "ù": "u", "ü": "u", "û": "u",
    "ç": "c", "ñ": "n",
  };
  s = s.replace(/[\u0103\u00E2\u00EE\u0219\u015F\u021B\u0163\u0102\u00C2\u00CE\u0218\u015E\u021A\u0162\u00E9\u00E8\u00EA\u00EB\u00E1\u00E0\u00E4\u00E3\u00EE\u00ED\u00EC\u00EF\u00F3\u00F2\u00F6\u00F4\u00FA\u00F9\u00FC\u00FB\u00E7\u00F1]/g, ch => map[ch] ?? ch);
  s = s
    .toLowerCase()
    .replace(/&/g, " si ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return s;
}

const EXTRA_CANVAS_PRODUCTS: any[] = EXTRA_CANVAS_LABELS.map((label) => {
  const slug = slugify(label);
  return {
    id: `canvas-${slug}`,
    slug,
    routeSlug: slug,
    title: label,
    description: `Tablou canvas personalizat – ${label.replace(/^Tablou\s+canvas\s+/i, "")}.`,
    priceBase: 79,
    currency: "RON",
    tags: ["canvas"],
    metadata: { category: "canvas" },
  };
});

// Afise (posters) – labels provided by maintainer
const EXTRA_AFISE_LABELS: string[] = [
  "Afiș program de lucru",
  "Afiș deschidem în curând",
  "Afiș orar magazin",
  "Afiș orar restaurant",
  "Afiș închis pentru inventar",
  "Afiș pauză de masă",
  "Afiș închis temporar",
  "Afiș deschis",
  "Afiș închis",
  "Afiș orar farmacie",
  "Afiș orar frizerie",
  "Afiș orar coafor",
  "Afiș orar cabinet medical",
  "Afiș orar stomatologie",
  "Afiș orar salon de înfrumusețare",
  "Afiș orar spălătorie auto",
  "Afiș orar service auto",
  "Afiș orar bar",
  "Afiș orar cafenea",
  "Afiș orar pizzerie",
  "Afiș orar fast food",
  "Afiș orar benzinărie",
  "Afiș orar magazin alimentar",
  "Afiș orar supermarket",
  "Afiș orar florărie",
  "Afiș orar librărie",
  "Afiș orar farmacie non stop",
  "Afiș orar non stop",
  "Afiș orar birou",
  "Afiș orar recepție",
  "Afiș program birou",
  "Afiș program restaurant",
  "Afiș program cafenea",
  "Afiș program de lucru magazin",
  "Afiș program de lucru firmă",
  "Afiș program de lucru salon",
  "Afiș program de lucru cabinet",
  "Afiș program de lucru service",
  "Afiș program de lucru farmacie",
  "Afiș program de lucru coafor",
  "Afiș program de lucru bar",
  "Afiș program de lucru restaurant",
  "Afiș program de lucru cafenea",
  "Afiș program de lucru fast food",
  "Afiș program de lucru firmă curierat",
  "Afiș program de lucru depozit",
  "Afiș program de lucru birou",
  "Afiș program de lucru weekend",
  "Afiș program de lucru sâmbătă",
  "Afiș program de lucru duminică",
  "Afiș deschis în weekend",
  "Afiș închis duminica",
  "Afiș închis sâmbăta",
  "Afiș pauză între ore",
  "Afiș orar de vară",
  "Afiș orar de iarnă",
  "Afiș orar special sărbători",
  "Afiș program sărbători",
  "Afiș deschis de Crăciun",
  "Afiș închis de Crăciun",
  "Afiș deschis de Paște",
  "Afiș închis de Paște",
  "Afiș închis 1 Mai",
  "Afiș închis de Revelion",
  "Afiș deschis non stop",
  "Afiș program zilnic",
  "Afiș orar zilnic",
  "Afiș orar personalizat",
  "Afiș program personalizat",
  "Afiș program companie",
  "Afiș program instituție",
  "Afiș program școală",
  "Afiș program grădiniță",
  "Afiș program clinică",
  "Afiș program cabinet veterinar",
  "Afiș program dentist",
  "Afiș program notar",
  "Afiș program avocat",
  "Afiș program bancă",
  "Afiș program poștă",
  "Afiș program transport",
  "Afiș program stație",
  "Afiș program orar clienți",
  "Afiș program acces public",
  "Afiș program intrare",
  "Afiș program ieșire",
  "Afiș deschidere nou magazin",
  "Afiș deschidere restaurant",
  "Afiș deschidere salon",
  "Afiș deschidere birou",
  "Afiș inaugurare",
  "Afiș lansare produs",
  "Afiș lansare film",
  "Afiș lansare campanie",
  "Afiș reducere",
  "Afiș promoție",
  "Afiș ofertă specială",
  "Afiș Black Friday",
  "Afiș reducere 50%",
  // Posters using the Afise configurator
  "Poster Ronaldo",
  "Poster Messi",
  "Poster Neymar",
  "Poster Jordan",
  "Poster Kobe",
  "Poster LeBron",
  "Poster Ferrari Red",
  "Poster Lamborghini",
  "Poster Porsche 911",
  "Poster Bugatti",
  "Poster Supercar Dream",
  "Poster Fast and Furious",
  "Poster Cinema Night",
  "Poster Deschidem în curând",
  "Poster Lansare film",
  "Poster Hollywood Night",
  "Poster Movie Premiere",
  "Poster Joker",
  "Poster The Godfather",
  "Poster Matrix",
  "Poster Spider-Man",
  "Poster Iron Man",
  "Poster Star Wars",
  "Poster Dune 2",
  "Poster Deadpool",
  "Poster Batman",
  "Poster Superman",
  "Poster Money Heist",
  "Poster Peaky Blinders",
  "Poster John Wick",
  "Poster 007 James Bond",
  "Poster Sport Icon",
  "Poster Street Art Car",
  "Poster Graffiti Urban",
  "Poster Luxury Life",
  "Poster Power Money",
  "Poster Wolf of Wall Street",
  "Poster Motorsport",
  "Poster Formula1",
  "Poster MotoGP",
  "Poster Racing Legend",
  "Poster Motivational Quote",
  "Poster Mindset Over Everything",
  "Poster Wildlife Tiger",
  "Poster Wildlife Lion",
  "Poster Wildlife Wolf",
  "Poster Ocean Waves",
  "Poster Mountain Landscape",
  "Poster City Skyline",
  "Poster Urban Night",
];

const EXTRA_AFISE_PRODUCTS: any[] = EXTRA_AFISE_LABELS.map((label) => {
  const clean = label.replace(/^Afiș\s*[–-]?\s*/i, "").replace(/^Afis\s*[–-]?\s*/i, "");
  const slug = slugify(clean);
  return {
    id: `afise-${slug}`,
    slug,
    routeSlug: slug,
    title: label,
    description: `Afiș personalizat – ${clean}.`,
    // priceBase left undefined to use category rules or explicit values later
    currency: "RON",
    tags: ["afise"],
    metadata: { category: "afise" },
  };
});

// Flayere (flyers) – labels provided by maintainer
const EXTRA_FLAYERE_LABELS: string[] = [
  "Flayer firmă",
  "Flayer promovare",
  "Flayer publicitar",
  "Flayer restaurant",
  "Flayer fast food",
  "Flayer cafenea",
  "Flayer salon înfrumusețare",
  "Flayer frizerie",
  "Flayer coafor",
  "Flayer cosmetică",
  "Flayer manichiură",
  "Flayer service auto",
  "Flayer spălătorie auto",
  "Flayer vulcanizare",
  "Flayer rent a car",
  "Flayer curățenie",
  "Flayer construcții",
  "Flayer firmă de transport",
  "Flayer mutări",
  "Flayer logistică",
  "Flayer curierat",
  "Flayer evenimente",
  "Flayer nuntă",
  "Flayer botez",
  "Flayer petrecere",
  "Flayer club",
  "Flayer concert",
  "Flayer lansare film",
  "Flayer festival",
  "Flayer deschidere magazin",
  "Flayer inaugurare",
  "Flayer ofertă specială",
  "Flayer reducere",
  "Flayer promoție",
  "Flayer Black Friday",
  "Flayer vânzare",
  "Flayer cumpărare",
  "Flayer vând apartament",
  "Flayer închiriez apartament",
  "Flayer vând casă",
  "Flayer teren de vânzare",
  "Flayer agenție imobiliară",
  "Flayer firmă construcții",
  "Flayer firmă electrică",
  "Flayer firmă instalații",
  "Flayer firmă curățenie",
  "Flayer firmă pază",
  "Flayer firmă contabilitate",
  "Flayer firmă IT",
  "Flayer magazin online",
  "Flayer firmă transport marfă",
  "Flayer firmă catering",
  "Flayer pizzerie",
  "Flayer restaurant delivery",
  "Flayer mâncare la domiciliu",
  "Flayer florărie",
  "Flayer brutărie",
  "Flayer patiserie",
  "Flayer cofetărie",
  "Flayer atelier croitorie",
  "Flayer atelier reparații",
  "Flayer magazin haine",
  "Flayer magazin încălțăminte",
  "Flayer magazin bijuterii",
  "Flayer magazin telefoane",
  "Flayer service telefoane",
  "Flayer magazin electrocasnice",
  "Flayer magazin mobilă",
  "Flayer magazin decor interior",
  "Flayer firmă design interior",
  "Flayer arhitectură",
  "Flayer firmă foto video",
  "Flayer studio foto",
  "Flayer fotograf nuntă",
  "Flayer DJ evenimente",
  "Flayer sonorizare",
  "Flayer lumină și sunet",
  "Flayer echipamente evenimente",
  "Flayer fitness",
  "Flayer sală de sport",
  "Flayer antrenor personal",
  "Flayer yoga",
  "Flayer masaj",
  "Flayer salon spa",
  "Flayer cabinet stomatologic",
  "Flayer cabinet veterinar",
  "Flayer farmacie",
  "Flayer centru medical",
  "Flayer școală de șoferi",
  "Flayer școală privată",
  "Flayer grădiniță",
  "Flayer cursuri engleză",
  "Flayer cursuri IT",
  "Flayer cursuri dans",
  "Flayer cursuri muzică",
  "Flayer recrutare personal",
  "Flayer angajări",
  "Flayer campanie politică",
  "Flayer campanie socială",
  "Flayer voluntariat",
  "Flayer salon de tatuaje",
  "Flayer barber shop",
  "Flayer magazin second hand",
  "Flayer magazin auto",
  "Flayer dealer auto",
  "Flayer spălătorie haine",
  "Flayer curățătorie chimică",
  "Flayer croitorie haine",
  "Flayer design vestimentar",
  "Flayer reparații pantofi",
  "Flayer atelier bijuterii",
  "Flayer atelier lemn",
  "Flayer tâmplărie PVC",
  "Flayer tâmplărie aluminiu",
  "Flayer termopane",
  "Flayer montaj acoperișuri",
  "Flayer renovări interioare",
  "Flayer finisaje interioare",
  "Flayer zugrav",
  "Flayer electrician autorizat",
  "Flayer instalator",
  "Flayer firmă de montaj",
  "Flayer firmă de transport persoane",
  "Flayer transport internațional",
  "Flayer transport colete",
  "Flayer tractări auto",
  "Flayer remorcări",
  "Flayer depozit logistic",
  "Flayer depozit materiale construcții",
  "Flayer instalații electrice",
  "Flayer instalații sanitare",
  "Flayer izolații termice",
  "Flayer hidroizolații",
  "Flayer vopsitorie auto",
  "Flayer tinichigerie",
  "Flayer spălătorie canapele",
  "Flayer curățare covoare",
  "Flayer spălare geamuri",
  "Flayer dezinsecție",
  "Flayer deratizare",
  "Flayer dezinfecție",
  "Flayer firmă de pază",
  "Flayer securitate clădiri",
  "Flayer protecție incendiu",
  "Flayer instruire PSI",
  "Flayer traduceri autorizate",
  "Flayer birou notarial",
  "Flayer cabinet avocatură",
  "Flayer cabinet psihologic",
  "Flayer cabinet kinetoterapie",
  "Flayer cabinet ortodontic",
  "Flayer optică medicală",
  "Flayer centru oftalmologic",
  "Flayer farmacie veterinară",
  "Flayer pensiune turistică",
  "Flayer hotel",
  "Flayer motel",
  "Flayer hostel",
  "Flayer camping",
  "Flayer agenție turism",
  "Flayer bilete avion",
  "Flayer excursii organizate",
  "Flayer city break",
  "Flayer închirieri auto",
  "Flayer rent apartments",
  "Flayer cazare apartamente",
  "Flayer închirieri utilaje",
  "Flayer închirieri scule",
  "Flayer firmă livrări",
  "Flayer livrare rapidă",
  "Flayer mâncare vegană",
  "Flayer burger house",
  "Flayer deserturi artizanale",
  "Flayer meniu prânz",
  "Flayer meniu pizza",
  "Flayer sucuri naturale",
  "Flayer băuturi artizanale",
  "Flayer cocktail bar",
  "Flayer lounge bar",
  "Flayer club de noapte",
  "Flayer eveniment corporate",
  "Flayer conferință business",
  "Flayer training profesional",
  "Flayer workshop",
  "Flayer seminar",
  "Flayer târg imobiliar",
  "Flayer târg auto",
  "Flayer târg de nunți",
  "Flayer târg handmade",
  "Flayer târg de Crăciun",
  "Flayer târg Paște",
  "Flayer flori 8 Martie",
  "Flayer cadouri Valentine’s Day",
  "Flayer reduceri de vară",
  "Flayer reduceri toamnă",
  "Flayer lichidare sezon",
  "Flayer campanie publicitară",
  "Flayer promovare online",
  "Flayer distribuție pliante",
  "Flayer promovare locală",
];

const EXTRA_FLAYERE_PRODUCTS: any[] = EXTRA_FLAYERE_LABELS.map((label) => {
  const clean = label.replace(/^Flaye?r\s*[–-]?\s*/i, "");
  const slug = slugify(clean);
  return {
    id: `flayere-${slug}`,
    slug,
    routeSlug: slug,
    title: label,
    description: `Flyer personalizat – ${clean}.`,
    currency: "RON",
    tags: ["flayere", "flyer"],
    metadata: { category: "flayere" },
  };
});

export const EXTRA_PRODUCTS_RAW: any[] = BASE_EXTRA_PRODUCTS_RAW.concat(
  EXTRA_CANVAS_PRODUCTS,
  EXTRA_AFISE_PRODUCTS,
  EXTRA_FLAYERE_PRODUCTS
);